FROM node:22.12.0-alpine AS frontend_builder
WORKDIR /app/front

COPY front/package.json front/package-lock.json ./
RUN npm ci

ARG VITE_MCP_PROXY_URL
ARG VITE_LOG_LEVEL
ENV VITE_MCP_PROXY_URL=$VITE_MCP_PROXY_URL
ENV VITE_LOG_LEVEL=$VITE_LOG_LEVEL

COPY front/ ./
RUN npm run build

FROM nginx:1.27-alpine

COPY --from=frontend_builder /app/front/dist /usr/share/nginx/html
COPY deployments/local/nginx.frontend.conf /etc/nginx/conf.d/default.conf
COPY deployments/local/nginx.sandbox.conf.template /etc/nginx/templates/sandbox.conf.template
COPY deployments/local/docker-entrypoint.sandbox-env.envsh /docker-entrypoint.d/10-sandbox-env.envsh
COPY deployments/local/docker-entrypoint.frontend-nginx.sh /docker-entrypoint.d/30-set-base-url.sh

RUN chmod +x /docker-entrypoint.d/10-sandbox-env.envsh \
    && chmod +x /docker-entrypoint.d/30-set-base-url.sh

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

