volumes:
    langgraph-data:
        driver: local

services:
    langgraph-postgres:
        image: postgres:16
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - langgraph-data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U postgres
            start_period: 10s
            timeout: 1s
            retries: 5
            interval: 5s

    langgraph-api:
        image: giga_agent
        depends_on:
            langgraph-redis:
                condition: service_healthy
            langgraph-postgres:
                condition: service_healthy
        environment:
            REDIS_URI: redis://langgraph-redis:6379
            POSTGRES_URI: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable
            JUPYTER_CLIENT_API: http://repl:9090
            TOOL_CLIENT_API: http://tool_server:9091
        volumes:
            - ./db/:/deps/graph/db/

    repl:
        user: jupyter
        command: uv run uvicorn app.main:app --host 0.0.0.0 --port 9090

    tool_server:
        image: giga_agent

    giga_agent_server:
        image: giga_agent
