"""init rag branch

Revision ID: 20fbc4e60762
Revises: 
Create Date: 2026-02-19 21:12:07.889141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20fbc4e60762'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('rag',)
depends_on: Union[str, Sequence[str], None] = '4c2d9e7a1b3f'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('embedding_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['embedding_id'], ['core_embeddings.id'], name='fk_rag_collections_embedding_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['core_users.id'], name='fk_rag_collections_owner_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_rag_collections_owner_name')
    )
    with op.batch_alter_table('rag_collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_collections_embedding_id'), ['embedding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_collections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_collections_owner_id'), ['owner_id'], unique=False)

    op.create_table('rag_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('original_name', sa.String(length=1024), nullable=False),
    sa.Column('sandbox_path', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['rag_collections.id'], name='fk_rag_documents_collection_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['core_users.id'], name='fk_rag_documents_owner_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rag_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_documents_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_documents_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rag_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_documents_owner_id'))
        batch_op.drop_index(batch_op.f('ix_rag_documents_id'))
        batch_op.drop_index(batch_op.f('ix_rag_documents_collection_id'))

    op.drop_table('rag_documents')
    with op.batch_alter_table('rag_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_collections_owner_id'))
        batch_op.drop_index(batch_op.f('ix_rag_collections_id'))
        batch_op.drop_index(batch_op.f('ix_rag_collections_embedding_id'))

    op.drop_table('rag_collections')
    # ### end Alembic commands ###

