"""add sandbox

Revision ID: ddcce36dc51c
Revises: 7d8a5e6f95c5
Create Date: 2026-02-10 15:57:56.503446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddcce36dc51c'
down_revision: Union[str, None] = '7d8a5e6f95c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_sandbox_providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('idle_timeout', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('core_sandbox_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_sandbox_providers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_sandbox_providers_owner_id'), ['owner_id'], unique=False)

    op.create_table('core_sandboxes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['core_sandbox_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'provider_id', name='uq_sandbox_owner_provider')
    )
    with op.batch_alter_table('core_sandboxes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_sandboxes_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_sandboxes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_sandboxes_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_sandboxes_provider_id'), ['provider_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_sandboxes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_sandboxes_provider_id'))
        batch_op.drop_index(batch_op.f('ix_core_sandboxes_owner_id'))
        batch_op.drop_index(batch_op.f('ix_core_sandboxes_id'))
        batch_op.drop_index(batch_op.f('ix_core_sandboxes_external_id'))

    op.drop_table('core_sandboxes')
    with op.batch_alter_table('core_sandbox_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_sandbox_providers_owner_id'))
        batch_op.drop_index(batch_op.f('ix_core_sandbox_providers_id'))

    op.drop_table('core_sandbox_providers')
    # ### end Alembic commands ###

