"""init

Revision ID: 7d8a5e6f95c5
Revises:
Create Date: 2026-02-09 11:05:54.939819

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7d8a5e6f95c5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "core_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "settings",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    with op.batch_alter_table("core_users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_core_users_id"), ["id"], unique=False)

    op.create_table(
        "core_llm_providers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "settings",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["core_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("core_llm_providers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_llm_providers_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_llm_providers_owner_id"), ["owner_id"], unique=False
        )

    op.create_table(
        "core_llms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("parallel_calls", sa.Integer(), nullable=False),
        sa.Column(
            "settings",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["core_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["core_llm_providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("core_llms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_core_llms_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_core_llms_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_llms_provider_id"), ["provider_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("core_llms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_llms_provider_id"))
        batch_op.drop_index(batch_op.f("ix_core_llms_owner_id"))
        batch_op.drop_index(batch_op.f("ix_core_llms_id"))

    op.drop_table("core_llms")
    with op.batch_alter_table("core_llm_providers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_llm_providers_owner_id"))
        batch_op.drop_index(batch_op.f("ix_core_llm_providers_id"))

    op.drop_table("core_llm_providers")
    with op.batch_alter_table("core_users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_users_id"))

    op.drop_table("core_users")
    # ### end Alembic commands ###
