"""add file model

Revision ID: 15623e5e3b01
Revises: ddcce36dc51c
Create Date: 2026-02-11 16:09:50.878327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15623e5e3b01'
down_revision: Union[str, None] = 'ddcce36dc51c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('sandbox_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['core_sandbox_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'provider_id', 'sandbox_path', name='uq_file_owner_provider_path')
    )
    with op.batch_alter_table('core_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_files_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_files_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_files_provider_id'), ['provider_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_files_provider_id'))
        batch_op.drop_index(batch_op.f('ix_core_files_owner_id'))
        batch_op.drop_index(batch_op.f('ix_core_files_id'))

    op.drop_table('core_files')
    # ### end Alembic commands ###
