"""add image generators

Revision ID: 22147ede27d9
Revises: 15623e5e3b01
Create Date: 2026-02-15 22:07:24.926705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22147ede27d9'
down_revision: Union[str, None] = '15623e5e3b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_image_generators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('llm_provider_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['llm_provider_id'], ['core_llm_providers.id'], name='fk_core_image_generators_llm_provider_id'),
    sa.ForeignKeyConstraint(['owner_id'], ['core_users.id'], name='fk_core_image_generators_owner_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('core_image_generators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_image_generators_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_image_generators_llm_provider_id'), ['llm_provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_image_generators_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('core_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_generator_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_core_users_image_generator_id'), ['image_generator_id'], unique=False)
        batch_op.create_foreign_key('fk_core_users_image_generator_id', 'core_image_generators', ['image_generator_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_core_users_image_generator_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_core_users_image_generator_id'))
        batch_op.drop_column('image_generator_id')

    with op.batch_alter_table('core_image_generators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_image_generators_owner_id'))
        batch_op.drop_index(batch_op.f('ix_core_image_generators_llm_provider_id'))
        batch_op.drop_index(batch_op.f('ix_core_image_generators_id'))

    op.drop_table('core_image_generators')
    # ### end Alembic commands ###

