"""init

Revision ID: a34df67f135a
Revises: 
Create Date: 2026-02-24 03:17:15.271695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a34df67f135a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('secrets', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('image_generator_id', sa.Uuid(), nullable=True),
    sa.Column('search_engine_id', sa.Uuid(), nullable=True),
    sa.Column('embedding_id', sa.Uuid(), nullable=True),
    sa.Column('llm_id', sa.Uuid(), nullable=True),
    sa.Column('fast_llm_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['embedding_id'], ['core_embeddings.id'], name='fk_core_users_embedding_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['fast_llm_id'], ['core_llms.id'], name='fk_core_users_fast_llm_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['image_generator_id'], ['core_image_generators.id'], name='fk_core_users_image_generator_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['llm_id'], ['core_llms.id'], name='fk_core_users_llm_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['search_engine_id'], ['core_search_engines.id'], name='fk_core_users_search_engine_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('core_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_users_embedding_id'), ['embedding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_users_fast_llm_id'), ['fast_llm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_users_image_generator_id'), ['image_generator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_users_llm_id'), ['llm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_users_search_engine_id'), ['search_engine_id'], unique=False)

    op.create_table('core_connectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['core_users.id'], name='fk_core_connectors_owner_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('core_connectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_connectors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_connectors_owner_id'), ['owner_id'], unique=False)

    op.create_table('core_sandbox_providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('idle_timeout', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('core_sandbox_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_sandbox_providers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_sandbox_providers_owner_id'), ['owner_id'], unique=False)

    op.create_table('core_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('vector_size', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['core_connectors.id'], name='fk_core_embeddings_connector_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['core_users.id'], name='fk_core_embeddings_owner_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('core_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_embeddings_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_embeddings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_embeddings_owner_id'), ['owner_id'], unique=False)

    op.create_table('core_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('sandbox_path', sa.String(length=1024), nullable=False),
    sa.Column('original_name', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['core_sandbox_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'provider_id', 'sandbox_path', name='uq_file_owner_provider_path')
    )
    with op.batch_alter_table('core_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_files_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_files_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_files_provider_id'), ['provider_id'], unique=False)

    op.create_table('core_image_generators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['core_connectors.id'], name='fk_core_image_generators_connector_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['core_users.id'], name='fk_core_image_generators_owner_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('core_image_generators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_image_generators_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_image_generators_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_image_generators_owner_id'), ['owner_id'], unique=False)

    op.create_table('core_llms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('parallel_calls', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['core_connectors.id'], name='fk_core_llms_connector_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['core_users.id'], name='fk_core_llms_owner_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('core_llms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_llms_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_llms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_llms_owner_id'), ['owner_id'], unique=False)

    op.create_table('core_sandboxes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['core_users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['core_sandbox_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'provider_id', name='uq_sandbox_owner_provider')
    )
    with op.batch_alter_table('core_sandboxes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_sandboxes_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_sandboxes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_sandboxes_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_sandboxes_provider_id'), ['provider_id'], unique=False)

    op.create_table('core_search_engines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['core_connectors.id'], name='fk_core_search_engines_connector_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['core_users.id'], name='fk_core_search_engines_owner_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('core_search_engines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_search_engines_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_search_engines_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_search_engines_owner_id'), ['owner_id'], unique=False)

    op.create_table('core_rag_collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('embedding_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['embedding_id'], ['core_embeddings.id'], name='fk_core_rag_collections_embedding_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['core_users.id'], name='fk_core_rag_collections_owner_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_core_rag_collections_owner_name')
    )
    with op.batch_alter_table('core_rag_collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_rag_collections_embedding_id'), ['embedding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_rag_collections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_rag_collections_owner_id'), ['owner_id'], unique=False)

    op.create_table('core_rag_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('original_name', sa.String(length=1024), nullable=False),
    sa.Column('sandbox_path', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['core_rag_collections.id'], name='fk_core_rag_documents_collection_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['core_users.id'], name='fk_core_rag_documents_owner_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('core_rag_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_rag_documents_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_rag_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_rag_documents_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_rag_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_rag_documents_owner_id'))
        batch_op.drop_index(batch_op.f('ix_core_rag_documents_id'))
        batch_op.drop_index(batch_op.f('ix_core_rag_documents_collection_id'))

    op.drop_table('core_rag_documents')
    with op.batch_alter_table('core_rag_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_rag_collections_owner_id'))
        batch_op.drop_index(batch_op.f('ix_core_rag_collections_id'))
        batch_op.drop_index(batch_op.f('ix_core_rag_collections_embedding_id'))

    op.drop_table('core_rag_collections')
    with op.batch_alter_table('core_search_engines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_search_engines_owner_id'))
        batch_op.drop_index(batch_op.f('ix_core_search_engines_id'))
        batch_op.drop_index(batch_op.f('ix_core_search_engines_connector_id'))

    op.drop_table('core_search_engines')
    with op.batch_alter_table('core_sandboxes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_sandboxes_provider_id'))
        batch_op.drop_index(batch_op.f('ix_core_sandboxes_owner_id'))
        batch_op.drop_index(batch_op.f('ix_core_sandboxes_id'))
        batch_op.drop_index(batch_op.f('ix_core_sandboxes_external_id'))

    op.drop_table('core_sandboxes')
    with op.batch_alter_table('core_llms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_llms_owner_id'))
        batch_op.drop_index(batch_op.f('ix_core_llms_id'))
        batch_op.drop_index(batch_op.f('ix_core_llms_connector_id'))

    op.drop_table('core_llms')
    with op.batch_alter_table('core_image_generators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_image_generators_owner_id'))
        batch_op.drop_index(batch_op.f('ix_core_image_generators_id'))
        batch_op.drop_index(batch_op.f('ix_core_image_generators_connector_id'))

    op.drop_table('core_image_generators')
    with op.batch_alter_table('core_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_files_provider_id'))
        batch_op.drop_index(batch_op.f('ix_core_files_owner_id'))
        batch_op.drop_index(batch_op.f('ix_core_files_id'))

    op.drop_table('core_files')
    with op.batch_alter_table('core_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_embeddings_owner_id'))
        batch_op.drop_index(batch_op.f('ix_core_embeddings_id'))
        batch_op.drop_index(batch_op.f('ix_core_embeddings_connector_id'))

    op.drop_table('core_embeddings')
    with op.batch_alter_table('core_sandbox_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_sandbox_providers_owner_id'))
        batch_op.drop_index(batch_op.f('ix_core_sandbox_providers_id'))

    op.drop_table('core_sandbox_providers')
    with op.batch_alter_table('core_connectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_connectors_owner_id'))
        batch_op.drop_index(batch_op.f('ix_core_connectors_id'))

    op.drop_table('core_connectors')
    with op.batch_alter_table('core_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_users_search_engine_id'))
        batch_op.drop_index(batch_op.f('ix_core_users_llm_id'))
        batch_op.drop_index(batch_op.f('ix_core_users_image_generator_id'))
        batch_op.drop_index(batch_op.f('ix_core_users_id'))
        batch_op.drop_index(batch_op.f('ix_core_users_fast_llm_id'))
        batch_op.drop_index(batch_op.f('ix_core_users_embedding_id'))

    op.drop_table('core_users')
    # ### end Alembic commands ###

