"""empty message

Revision ID: cb8c1f67cd6c
Revises: 1d2b3c4d5e6f
Create Date: 2026-04-02 18:01:50.758379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb8c1f67cd6c'
down_revision: Union[str, None] = '1d2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_channel_bots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('bot_username', sa.String(length=255), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core_users.id'], name='fk_core_channel_bots_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('core_channel_bots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_channel_bots_channel_type'), ['channel_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_channel_bots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_channel_bots_user_id'), ['user_id'], unique=False)

    op.create_table('core_channel_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bot_id', sa.Uuid(), nullable=False),
    sa.Column('external_chat_id', sa.String(length=255), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=True),
    sa.Column('chat_type', sa.String(length=100), nullable=True),
    sa.Column('chat_title', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['core_channel_bots.id'], name='fk_core_channel_contacts_bot_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('core_channel_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_channel_contacts_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_channel_contacts_external_chat_id'), ['external_chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_channel_contacts_external_user_id'), ['external_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_channel_contacts_id'), ['id'], unique=False)

    op.create_table('core_channel_threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bot_id', sa.Uuid(), nullable=False),
    sa.Column('external_chat_id', sa.String(length=255), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=True),
    sa.Column('langgraph_thread_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['core_channel_bots.id'], name='fk_core_channel_threads_bot_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('core_channel_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_channel_threads_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_channel_threads_external_chat_id'), ['external_chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_channel_threads_external_user_id'), ['external_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_channel_threads_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_channel_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_channel_threads_id'))
        batch_op.drop_index(batch_op.f('ix_core_channel_threads_external_user_id'))
        batch_op.drop_index(batch_op.f('ix_core_channel_threads_external_chat_id'))
        batch_op.drop_index(batch_op.f('ix_core_channel_threads_bot_id'))

    op.drop_table('core_channel_threads')
    with op.batch_alter_table('core_channel_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_channel_contacts_id'))
        batch_op.drop_index(batch_op.f('ix_core_channel_contacts_external_user_id'))
        batch_op.drop_index(batch_op.f('ix_core_channel_contacts_external_chat_id'))
        batch_op.drop_index(batch_op.f('ix_core_channel_contacts_bot_id'))

    op.drop_table('core_channel_contacts')
    with op.batch_alter_table('core_channel_bots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_channel_bots_user_id'))
        batch_op.drop_index(batch_op.f('ix_core_channel_bots_id'))
        batch_op.drop_index(batch_op.f('ix_core_channel_bots_channel_type'))

    op.drop_table('core_channel_bots')
    # ### end Alembic commands ###

