"""add agent profiles and mcp catalog id

Revision ID: ff60fb3fd873
Revises: 5a7c9e1f3b20
Create Date: 2026-08-09 15:32:58.370629

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ff60fb3fd873"
down_revision: Union[str, None] = "5a7c9e1f3b20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "core_agent_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("builtin_ref", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=128), nullable=True),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "modules",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "tool_policy",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "examples",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("llm_id", sa.Uuid(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('custom', 'builtin_override')",
            name="ck_core_agent_profiles_source",
        ),
        sa.CheckConstraint(
            "(source = 'custom' AND builtin_ref IS NULL) OR "
            "(source = 'builtin_override' AND builtin_ref IS NOT NULL)",
            name="ck_core_agent_profiles_builtin_ref",
        ),
        sa.ForeignKeyConstraint(["llm_id"], ["core_llms.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["core_users.id"],
            name="fk_core_agent_profiles_owner_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_id", "builtin_ref", name="uq_core_agent_profile_builtin_owner"
        ),
    )
    with op.batch_alter_table("core_agent_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_agent_profiles_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_agent_profiles_owner_id"), ["owner_id"], unique=False
        )

    op.create_table(
        "core_agent_connector_bindings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("catalog_id", sa.String(length=128), nullable=False),
        sa.Column("mcp_server_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mcp_server_id"], ["core_mcp_servers.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["core_agent_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "profile_id", "catalog_id", name="uq_agent_connector_requirement"
        ),
    )
    with op.batch_alter_table("core_agent_connector_bindings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_agent_connector_bindings_profile_id"),
            ["profile_id"],
            unique=False,
        )

    op.create_table(
        "core_agent_skill_bindings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_name", sa.String(length=128), nullable=False),
        sa.Column("source", sa.String(length=2048), nullable=True),
        sa.Column("source_ref", sa.String(length=255), nullable=True),
        sa.Column("skill_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_commit", sa.String(length=64), nullable=True),
        sa.Column("content_hash", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["core_agent_profiles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["skill_id"], ["core_skills.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "profile_id", "requirement_name", name="uq_agent_skill_requirement"
        ),
    )
    with op.batch_alter_table("core_agent_skill_bindings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_agent_skill_bindings_profile_id"),
            ["profile_id"],
            unique=False,
        )

    with op.batch_alter_table(
        "core_mcp_servers", schema=None, recreate="never"
    ) as batch_op:
        batch_op.add_column(
            sa.Column("catalog_id", sa.String(length=128), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_core_mcp_servers_catalog_id"), ["catalog_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "core_mcp_servers", schema=None, recreate="never"
    ) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_mcp_servers_catalog_id"))
        batch_op.drop_column("catalog_id")

    with op.batch_alter_table("core_agent_skill_bindings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_agent_skill_bindings_profile_id"))

    op.drop_table("core_agent_skill_bindings")
    with op.batch_alter_table("core_agent_connector_bindings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_agent_connector_bindings_profile_id"))

    op.drop_table("core_agent_connector_bindings")
    with op.batch_alter_table("core_agent_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_agent_profiles_owner_id"))
        batch_op.drop_index(batch_op.f("ix_core_agent_profiles_id"))

    op.drop_table("core_agent_profiles")
    # ### end Alembic commands ###
