"""add core resource permissions

Revision ID: a6243e1c9b3f
Revises: 931393cce043
Create Date: 2026-02-28 20:46:27.476813

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6243e1c9b3f"
down_revision: Union[str, None] = "931393cce043"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "core_resource_permissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("resource_type", sa.Text(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("owner_type", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("permission", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "resource_type",
            "resource_id",
            "owner_type",
            "owner_id",
            "permission",
            name="uq_core_resource_permissions_resource_owner_perm",
        ),
    )
    with op.batch_alter_table("core_resource_permissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_resource_permissions_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_resource_permissions_owner_id"),
            ["owner_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_core_resource_permissions_resource_id"),
            ["resource_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("core_resource_permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_resource_permissions_resource_id"))
        batch_op.drop_index(batch_op.f("ix_core_resource_permissions_owner_id"))
        batch_op.drop_index(batch_op.f("ix_core_resource_permissions_id"))

    op.drop_table("core_resource_permissions")
    # ### end Alembic commands ###
