"""add rate_limit table

Revision ID: ed56338cb9b2
Revises: 7e1f4c2a9b15
Create Date: 2026-06-02 00:18:47.567481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed56338cb9b2'
down_revision: Union[str, None] = '7e1f4c2a9b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_rate_limits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('requests_global', sa.Integer(), nullable=True),
    sa.Column('requests_per_user', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type', 'resource_id', name='uq_core_rate_limits_resource')
    )
    with op.batch_alter_table('core_rate_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_rate_limits_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_rate_limits_resource_id'), ['resource_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_rate_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_rate_limits_resource_id'))
        batch_op.drop_index(batch_op.f('ix_core_rate_limits_id'))

    op.drop_table('core_rate_limits')
    # ### end Alembic commands ###

