"""add core groups and group members

Revision ID: 931393cce043
Revises: 9b7d4ac31f22
Create Date: 2026-02-28 00:31:42.618924

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "931393cce043"
down_revision: Union[str, None] = "9b7d4ac31f22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "core_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "permissions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["core_users.id"], name="fk_core_groups_owner_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "name", name="uq_core_groups_owner_name"),
    )
    with op.batch_alter_table("core_groups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_core_groups_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_core_groups_owner_id"), ["owner_id"], unique=False
        )

    op.create_table(
        "core_group_members",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["core_groups.id"],
            name="fk_core_group_members_group_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["core_users.id"],
            name="fk_core_group_members_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id"),
    )
    with op.batch_alter_table("core_group_members", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_core_group_members_group_id"), ["group_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_core_group_members_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("core_group_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_group_members_user_id"))
        batch_op.drop_index(batch_op.f("ix_core_group_members_group_id"))

    op.drop_table("core_group_members")
    with op.batch_alter_table("core_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_core_groups_owner_id"))
        batch_op.drop_index(batch_op.f("ix_core_groups_id"))

    op.drop_table("core_groups")
    # ### end Alembic commands ###
