name: Lint Repl

on:
  push:
    paths:
      - 'backend/repl/**'
  pull_request:
    paths:
      - 'backend/repl/**'
  merge_group:

jobs:
  lint-repl:
    name: Lint Repl
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/repl
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.29"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: uv sync --group lint

      - name: Run lint
        run: make lint

