from datetime import timedelta
from typing import Annotated
import uuid

import jwt
from jwt.exceptions import ExpiredSignatureError, PyJWTError
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordRequestForm, OAuth2PasswordBearer
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from giga_agent.core.db import get_session
from giga_agent.auth import schemas, models, security
from giga_agent.auth.security import ACCESS_TOKEN_EXPIRE_MINUTES
from giga_agent.core.events import event_bus
from giga_agent.auth.events import UserCreatedEvent

router = APIRouter(tags=["auth"])

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="token")

async def get_user_by_email(db: AsyncSession, email: str):
    result = await db.execute(select(models.User).where(models.User.email == email))
    return result.scalar_one_or_none()

async def get_user_by_uuid(db: AsyncSession, user_id: uuid.UUID):
    result = await db.execute(select(models.User).where(models.User.id == user_id))
    return result.scalar_one_or_none()

async def get_current_user(token: Annotated[str, Depends(oauth2_scheme)], db: Annotated[AsyncSession, Depends(get_session)]):
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials",
        headers={"WWW-Authenticate": "Bearer"},
    )
    token_expired_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Token expired",
        headers={"WWW-Authenticate": "Bearer"},
    )
    try:
        payload = jwt.decode(token, security.SECRET_KEY, algorithms=[security.ALGORITHM])
        user_id_str: str = payload.get("user_id")
        
        if user_id_str is None:
            raise credentials_exception
            
        token_data = schemas.TokenData(user_id=uuid.UUID(user_id_str))
        
    except ExpiredSignatureError:
        raise token_expired_exception
    except PyJWTError:
        raise credentials_exception
    except ValueError: # Invalid UUID string
        raise credentials_exception
    
    user = await get_user_by_uuid(db, user_id=token_data.user_id)
    if user is None:
        raise credentials_exception
    return user

async def get_current_active_user(current_user: Annotated[models.User, Depends(get_current_user)]):
    if not current_user.is_active:
        raise HTTPException(status_code=400, detail="Inactive user")
    return current_user

@router.post("/token", response_model=schemas.Token)
async def login_for_access_token(
    form_data: Annotated[OAuth2PasswordRequestForm, Depends()],
    db: Annotated[AsyncSession, Depends(get_session)]
):
    user = await get_user_by_email(db, form_data.username)
    if not user or not security.verify_password(form_data.password, user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect username or password",
            headers={"WWW-Authenticate": "Bearer"},
        )
    access_token_expires = timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    
    # Include user_id in token as requested
    access_token = security.create_access_token(
        data={
            "sub": user.email, 
            "user_id": str(user.id)
        }, 
        expires_delta=access_token_expires
    )
    return {"access_token": access_token, "token_type": "bearer"}

@router.get("/users/me", response_model=schemas.User)
async def read_users_me(
    current_user: Annotated[models.User, Depends(get_current_active_user)]
):
    return current_user

@router.post("/users", response_model=schemas.User)
async def create_user(
    user: schemas.UserCreate,
    db: Annotated[AsyncSession, Depends(get_session)],
    current_user: Annotated[models.User, Depends(get_current_active_user)] 
):
    db_user = await get_user_by_email(db, user.email)
    if db_user:
        raise HTTPException(status_code=400, detail="Email already registered")
    
    hashed_password = security.get_password_hash(user.password)
    
    # ID is automatically generated by default factory
    db_user = models.User(
        email=user.email, 
        hashed_password=hashed_password,
        is_active=user.is_active,
        is_superuser=user.is_superuser
    )
    db.add(db_user)
    await db.commit()
    await db.refresh(db_user)

    await event_bus.publish(UserCreatedEvent(
        user_id=db_user.id,
        email=db_user.email
    ))

    return db_user
